[package]
name = "fluent_field_assertions"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
pretty_assertions = "1"
proc-macro-error = "1.0"
proc-macro2 = { version = "1.0", default-features = false }
quote = "1"
syn = "2"

[dev-dependencies]
rstest = "0"

